RH-34891: Use request limit for Grandtrunk
roihunter/gold-digger pull request #251
Opened 2021-09-30 14:08 UTC by asuba512

https://roihunter.atlassian.net/browse/RH-34891

It's a bit messy with each API having a bit different behavior. I considered returning the response from `Provider._get` always, and thus not having to override it for Grandtrunk (and as it is for Frankfurter already), but that would require us to add some additional checks for the status code to all other providers. This way it's probably less code.

@roihunter/pythonistas Please take a look :-)

2021-09-30 15:03 UTC, miso-belica commented on gold_digger/data_providers/_provider.py
> +    STATUS_CODE_503_SERVICE_UNAVAILABLE = 503
There is a [new module from Python 3.5](https://dev.to/misobelica/python-features-by-version-3318#python-35-20200930). You can use it instead here.

```python
from HTTP import HTTPStatus

assert HTTPStatus.OK == 200
assert HTTPStatus.SERVICE_UNAVAILABLE == 503
```

Yes, I am bored, thanks for asking :D

2021-10-05 08:43 UTC, harpener requested changes
@asuba512 Nice changes, but please fix the logic. :-)

2021-10-05 08:43 UTC, harpener commented on gold_digger/data_providers/grandtrunk.py
> +        if response.status_code == HTTPStatus.SERVICE_UNAVAILABLE:
@asuba512 This logic will never work like this, because the response object evaluates false if the status code is >= 400. :-)

2021-10-05 08:43 UTC, harpener commented on gold_digger/data_providers/grandtrunk.py
> +        :type params: dict[str, str]
```suggestion
        :type params: None | dict[str, str]
```

2021-10-05 08:46 UTC, harpener commented on gold_digger/data_providers/grandtrunk.py
> +            return currencies
@asuba512 Btw, maybe you could initialize the variable later and return the literal here to make it more visible. Or do you prefer having it named to show its context? :-)

2021-10-05 09:59 UTC, asuba512 commented on gold_digger/data_providers/grandtrunk.py
> +            return currencies
I don't mine either :-). In this case the variable doesn't even have to be initialized, as it's value isn't used anywhere apart the return statements here. I'll return `None` instead :-).

2021-10-05 10:03 UTC, harpener commented on gold_digger/data_providers/grandtrunk.py
> +            return currencies
Not `None`, `set()` 🙈

2021-10-05 10:03 UTC, asuba512 commented on gold_digger/data_providers/grandtrunk.py
> +            return currencies
:cry:

2021-10-05 10:26 UTC, harpener approved these changes
👍

2021-10-05 10:27 UTC, merged